/* Generated By:JJTree: Do not edit this line. ASTAssignedIdentifier.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.tysonite.asn1.parser;

public
class ASTAssignedIdentifier extends SimpleNode {
  public ASTAssignedIdentifier(int id) {
    super(id);
  }

  public ASTAssignedIdentifier(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=92bee2cf4c2875b06d63b45b03f85853 (do not edit this line) */
