/* Generated By:JJTree: Do not edit this line. ASTBuiltinType.java Version 6.1 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.tysonite.asn1.parser;

public class ASTBuiltinType extends SimpleNode {

   private int type = -1;

   public ASTBuiltinType(int id) {
      super(id);
   }

   public ASTBuiltinType(AsnParser p, int id) {
      super(p, id);
   }

   public void setType(int type) {
      this.type = type;
   }

   public int getType() {
      return type;
   }

   /**
    * Accept the visitor. *
    */
   public Object jjtAccept(AsnParserVisitor visitor, Object data) {

      return visitor.visit(this, data);
   }
}
/* JavaCC - OriginalChecksum=e883b1baa3a37ea0414b27bc14e05046 (do not edit this line) */
