/* Generated By:JJTree: Do not edit this line. ASTContainedSubtype.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.tysonite.asn1.parser;

public
class ASTContainedSubtype extends SimpleNode {
  public ASTContainedSubtype(int id) {
    super(id);
  }

  public ASTContainedSubtype(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=aa4dec8583ec56adb124fdac162cd08f (do not edit this line) */
