/* Generated By:JJTree: Do not edit this line. ASTClassNumber.java Version 6.1 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.tysonite.asn1.parser;

public class ASTClassNumber extends SimpleNode {

   private int tagNumber;

   public ASTClassNumber(int id) {
      super(id);
   }

   public ASTClassNumber(AsnParser p, int id) {
      super(p, id);
   }

   public void setTagNumber(int tagNumber) {
      this.tagNumber = tagNumber;
   }

   public int getTagNumber() {
      return this.tagNumber;
   }

   /**
    * Accept the visitor. *
    */
   public Object jjtAccept(AsnParserVisitor visitor, Object data) {

      return visitor.visit(this, data);
   }
}
/* JavaCC - OriginalChecksum=289de0ab63467fd82fbac4eaa5527a24 (do not edit this line) */
