/* Generated By:JJTree: Do not edit this line. ASTDefinedMacroType.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.tysonite.asn1.parser;

public
class ASTDefinedMacroType extends SimpleNode {
  public ASTDefinedMacroType(int id) {
    super(id);
  }

  public ASTDefinedMacroType(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9b6f003a6c191d57091c474a2d19b5df (do not edit this line) */
