/* Generated By:JJTree: Do not edit this line. ASTElementType.java Version 6.1 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.tysonite.asn1.parser;

public class ASTElementType extends SimpleNode {

   private boolean isOptional = false;
   private boolean hasDefault = false;

   public ASTElementType(int id) {
      super(id);
   }

   public ASTElementType(AsnParser p, int id) {
      super(p, id);
   }

   public void setOptional(boolean isOptional) {
      this.isOptional = isOptional;
   }

   public boolean isOptional() {
      return isOptional;
   }

   public void setDefault(boolean hasDefault) {
      this.hasDefault = hasDefault;
   }

   public boolean hasDefault() {
      return hasDefault;
   }

   /**
    * Accept the visitor. *
    */
   public Object jjtAccept(AsnParserVisitor visitor, Object data) {

      return visitor.visit(this, data);
   }
}
/* JavaCC - OriginalChecksum=b95505ae48c81de390988ce9e7b95406 (do not edit this line) */
