/* Generated By:JJTree: Do not edit this line. ASTExportSymbolList.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.tysonite.asn1.parser;

public
class ASTExportSymbolList extends SimpleNode {
  public ASTExportSymbolList(int id) {
    super(id);
  }

  public ASTExportSymbolList(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=07acc7f5fcde5fb10f0651b7f85f358a (do not edit this line) */
