/* Generated By:JJTree: Do not edit this line. ASTModuleDefinition.java Version 6.1 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.tysonite.asn1.parser;

public class ASTModuleDefinition extends SimpleNode {

   public static int EXPLICIT = 1;
   public static int IMPLICIT = 2;
   public static int AUTOMATIC = 3;
   private int tag = EXPLICIT;

   public ASTModuleDefinition(int id) {
      super(id);
   }

   public ASTModuleDefinition(AsnParser p, int id) {
      super(p, id);
   }

   public void setTag(int tag) {
      this.tag = tag;
   }

   public int getTag() {
      return this.tag;
   }

   /**
    * Accept the visitor. *
    */
   public Object jjtAccept(AsnParserVisitor visitor, Object data) {

      return visitor.visit(this, data);
   }
}
/* JavaCC - OriginalChecksum=10df962b6a879b5da5f30709e8ef3dca (do not edit this line) */
