/* Generated By:JJTree: Do not edit this line. ASTNamedNumberList.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.tysonite.asn1.parser;

public
class ASTNamedNumberList extends SimpleNode {
  public ASTNamedNumberList(int id) {
    super(id);
  }

  public ASTNamedNumberList(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ad5f62abc078e5c3c9e67f797e52d199 (do not edit this line) */
