/* Generated By:JJTree: Do not edit this line. ASTNamedConstraint.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.tysonite.asn1.parser;

public
class ASTNamedConstraint extends SimpleNode {
  public ASTNamedConstraint(int id) {
    super(id);
  }

  public ASTNamedConstraint(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9ef6a7ab21082c00a3c9adaac411afbd (do not edit this line) */
