/* Generated By:JJTree: Do not edit this line. ASTObjIdComponent.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.tysonite.asn1.parser;

public
class ASTObjIdComponent extends SimpleNode {
  public ASTObjIdComponent(int id) {
    super(id);
  }

  public ASTObjIdComponent(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e74c2476d122f0a4374e139a96ce515c (do not edit this line) */
