/* Generated By:JJTree: Do not edit this line. ASTOctetStringType.java Version 6.1 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.tysonite.asn1.parser;

public class ASTOctetStringType extends SimpleNode {

   public enum StringType {

      OCTET_STRING,
      PRINTABLE_STRING,
      GENERALIZED_TIME,
      UTC_TIME,
      GRAPHIC_STRING,
      IA5_STRING,
      NUMERIC_STRING,
      TELETEX_STRING,
      UNKNOWN,
   };
   private StringType type = StringType.UNKNOWN;

   public ASTOctetStringType(int id) {
      super(id);
   }

   public ASTOctetStringType(AsnParser p, int id) {
      super(p, id);
   }

   public void setType(StringType type) {
      this.type = type;
   }

   public StringType getType() {
      return type;
   }

   /**
    * Accept the visitor. *
    */
   public Object jjtAccept(AsnParserVisitor visitor, Object data) {

      return visitor.visit(this, data);
   }
}
/* JavaCC - OriginalChecksum=f2287d6f067617f8b4eff9f0b0025a5c (do not edit this line) */
