/* Generated By:JJTree: Do not edit this line. ASTObjIdComponentList.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.tysonite.asn1.parser;

public
class ASTObjIdComponentList extends SimpleNode {
  public ASTObjIdComponentList(int id) {
    super(id);
  }

  public ASTObjIdComponentList(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1ad578a54d6fc9667d9128c3b3a291ba (do not edit this line) */
