/* Generated By:JJTree: Do not edit this line. ASTPermittedAlphabet.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.tysonite.asn1.parser;

public
class ASTPermittedAlphabet extends SimpleNode {
  public ASTPermittedAlphabet(int id) {
    super(id);
  }

  public ASTPermittedAlphabet(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=95899585f57c83bf6ae5571fc32aa8aa (do not edit this line) */
