/* Generated By:JJTree: Do not edit this line. ASTPresenceConstraint.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.tysonite.asn1.parser;

public
class ASTPresenceConstraint extends SimpleNode {
  public ASTPresenceConstraint(int id) {
    super(id);
  }

  public ASTPresenceConstraint(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f6d700f3007f513cb8e5efc358943408 (do not edit this line) */
