/* Generated By:JJTree: Do not edit this line. ASTSignedNumber.java Version 6.1 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.tysonite.asn1.parser;

public class ASTSignedNumber extends SimpleNode {

   private String n = null;

   public ASTSignedNumber(int id) {
      super(id);
   }

   public ASTSignedNumber(AsnParser p, int id) {
      super(p, id);
   }

   public void setNumber(String n) {
      this.n = n;
   }

   public String getNumber() {
      return n;
   }

   /**
    * Accept the visitor. *
    */
   public Object jjtAccept(AsnParserVisitor visitor, Object data) {

      return visitor.visit(this, data);
   }
}
/* JavaCC - OriginalChecksum=b348695ee7af6fd2e034784a856466c8 (do not edit this line) */
