/* Generated By:JJTree: Do not edit this line. ASTSnmpStatus.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.tysonite.asn1.parser;

public
class ASTSnmpStatus extends SimpleNode {
  public ASTSnmpStatus(int id) {
    super(id);
  }

  public ASTSnmpStatus(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c6a546904c42f89beaf91a84617cbb7f (do not edit this line) */
