/* Generated By:JJTree: Do not edit this line. ASTSelectionType.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.tysonite.asn1.parser;

public
class ASTSelectionType extends SimpleNode {
  public ASTSelectionType(int id) {
    super(id);
  }

  public ASTSelectionType(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=09e6ba9d030ea9bacc7c7bbabbd4f5c7 (do not edit this line) */
