/* Generated By:JJTree: Do not edit this line. ASTSnmpDescrPart.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.tysonite.asn1.parser;

public
class ASTSnmpDescrPart extends SimpleNode {
  public ASTSnmpDescrPart(int id) {
    super(id);
  }

  public ASTSnmpDescrPart(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8ac10272e21ed0aa6bee3c16fe819aac (do not edit this line) */
