/* Generated By:JJTree: Do not edit this line. ASTskip_to_matching_brace.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.tysonite.asn1.parser;

public
class ASTskip_to_matching_brace extends SimpleNode {
  public ASTskip_to_matching_brace(int id) {
    super(id);
  }

  public ASTskip_to_matching_brace(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=daf6c6467e9cf55f3f7567a7f37560a9 (do not edit this line) */
