/* Generated By:JJTree: Do not edit this line. ASTSnmpObjectTypeMacroType.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.tysonite.asn1.parser;

public
class ASTSnmpObjectTypeMacroType extends SimpleNode {
  public ASTSnmpObjectTypeMacroType(int id) {
    super(id);
  }

  public ASTSnmpObjectTypeMacroType(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=30c266fce66a91f8b97c6cb4beab8889 (do not edit this line) */
