/* Generated By:JJTree: Do not edit this line. ASTSpecialRealValue.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.tysonite.asn1.parser;

public
class ASTSpecialRealValue extends SimpleNode {
  public ASTSpecialRealValue(int id) {
    super(id);
  }

  public ASTSpecialRealValue(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=06329ee1e8d2719bd66bb284073c5437 (do not edit this line) */
