/* Generated By:JJTree: Do not edit this line. ASTSymbolsExported.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.tysonite.asn1.parser;

public
class ASTSymbolsExported extends SimpleNode {
  public ASTSymbolsExported(int id) {
    super(id);
  }

  public ASTSymbolsExported(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=609d70f90424d4875a5a7d102e1d33c2 (do not edit this line) */
