/* Generated By:JJTree: Do not edit this line. ASTSetOrSequenceType.java Version 6.1 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.tysonite.asn1.parser;

public class ASTSetOrSequenceType extends SimpleNode {

   public static final int SEQUENCE = 0;
   public static final int SET = 1;
   int choosenType = -1;

   public void setType(int type) {
      choosenType = type;
   }

   public int getType() {
      return this.choosenType;
   }

   public boolean isSequence() {
      return choosenType == SEQUENCE;
   }

   public boolean isSet() {
      return choosenType == SET;
   }

   public ASTSetOrSequenceType(int id) {
      super(id);
   }

   public ASTSetOrSequenceType(AsnParser p, int id) {
      super(p, id);
   }

   /**
    * Accept the visitor. *
    */
   public Object jjtAccept(AsnParserVisitor visitor, Object data) {

      return visitor.visit(this, data);
   }
}
/* JavaCC - OriginalChecksum=8d1c63523ad1802a976109dcf83905ee (do not edit this line) */
