/* Generated By:JJTree: Do not edit this line. ASTTypeOrValue.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.tysonite.asn1.parser;

public
class ASTTypeOrValue extends SimpleNode {
  public ASTTypeOrValue(int id) {
    super(id);
  }

  public ASTTypeOrValue(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a645e864068aaa0fe82ff65c999f85a6 (do not edit this line) */
