/* Generated By:JJTree: Do not edit this line. ASTValueConstraint.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.tysonite.asn1.parser;

public
class ASTValueConstraint extends SimpleNode {
  public ASTValueConstraint(int id) {
    super(id);
  }

  public ASTValueConstraint(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b9c7254e37be535aed40dc355d68e748 (do not edit this line) */
