/* Generated By:JJTree: Do not edit this line. SimpleNode.java Version 6.1 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.tysonite.asn1.parser;

public class SimpleNode implements Node {

   protected Node parent;
   protected Node[] children;
   protected int id;
   protected Object value;
   protected AsnParser parser;
   protected Token firstToken;
   protected Token lastToken;
   protected boolean isProcessed = false;

   public SimpleNode(int i) {
      id = i;
   }

   public SimpleNode(AsnParser p, int i) {
      this(i);
      parser = p;
   }

   public void markAsProcessed() {
      isProcessed = true;
   }

   public boolean isProcessed() {
      return isProcessed;
   }

   public void jjtOpen() {
   }

   public void jjtClose() {
   }

   public void jjtSetParent(Node n) {
      parent = n;
   }

   public Node jjtGetParent() {
      return parent;
   }

   public void jjtAddChild(Node n, int i) {
      if (children == null) {
         children = new Node[i + 1];
      } else if (i >= children.length) {
         Node c[] = new Node[i + 1];
         System.arraycopy(children, 0, c, 0, children.length);
         children = c;
      }
      children[i] = n;
   }

   public Node jjtGetChild(int i) {
      return children[i];
   }

   public int jjtGetNumChildren() {
      return (children == null) ? 0 : children.length;
   }

   public void jjtSetValue(Object value) {
      this.value = value;
   }

   public Object jjtGetValue() {
      return value;
   }

   public Token jjtGetFirstToken() {
      return firstToken;
   }

   public void jjtSetFirstToken(Token token) {
      this.firstToken = token;
   }

   public Token jjtGetLastToken() {
      return lastToken;
   }

   public void jjtSetLastToken(Token token) {
      this.lastToken = token;
   }

   /**
    * Accept the visitor. *
    */
   public Object jjtAccept(AsnParserVisitor visitor, Object data) {
      return visitor.visit(this, data);
   }

   /**
    * Accept the visitor. *
    */
   public Object childrenAccept(AsnParserVisitor visitor, Object data) {
      if (children != null) {
         for (int i = 0; i < children.length; ++i) {
            children[i].jjtAccept(visitor, data);
         }
      }
      return data;
   }

   /* You can override these two methods in subclasses of SimpleNode to
     customize the way the node appears when the tree is dumped.  If
     your output uses more than one line you should override
     toString(String), otherwise overriding toString() is probably all
     you need to do. */
   public String toString() {
      return AsnParserTreeConstants.jjtNodeName[id];
   }

   public String toString(String prefix) {
      return prefix + toString();
   }

   /* Override this method if you want to customize how the node dumps
     out its children. */
   public void dump(String prefix) {
      System.out.println(toString(prefix));
      if (children != null) {
         for (int i = 0; i < children.length; ++i) {
            SimpleNode n = (SimpleNode) children[i];
            if (n != null) {
               n.dump(prefix + " ");
            }
         }
      }
   }

   public int getId() {
      return id;
   }
}

/* JavaCC - OriginalChecksum=da649ab5b09ac04a71e9443d3a9b6d9b (do not edit this line) */
