/* Generated By:JJTree&JavaCC: Do not edit this line. AsnParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AsnParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OBJECT_IDENTIFIER_TKN = 8;
  /** RegularExpression Id. */
  int BSTRING_TKN = 9;
  /** RegularExpression Id. */
  int HSTRING_TKN = 10;
  /** RegularExpression Id. */
  int CSTRING_TKN = 11;
  /** RegularExpression Id. */
  int NUMBER_ERANGE_TKN = 12;
  /** RegularExpression Id. */
  int NUMBER_TKN = 13;
  /** RegularExpression Id. */
  int DOT_TKN = 14;
  /** RegularExpression Id. */
  int COMMA_TKN = 15;
  /** RegularExpression Id. */
  int LEFTBRACE_TKN = 16;
  /** RegularExpression Id. */
  int RIGHTBRACE_TKN = 17;
  /** RegularExpression Id. */
  int LEFTPAREN_TKN = 18;
  /** RegularExpression Id. */
  int RIGHTPAREN_TKN = 19;
  /** RegularExpression Id. */
  int LEFTBRACKET_TKN = 20;
  /** RegularExpression Id. */
  int RIGHTBRACKET_TKN = 21;
  /** RegularExpression Id. */
  int LESSTHAN_TKN = 22;
  /** RegularExpression Id. */
  int MINUS_TKN = 23;
  /** RegularExpression Id. */
  int GETS_TKN = 24;
  /** RegularExpression Id. */
  int BAR_TKN = 25;
  /** RegularExpression Id. */
  int SEMI_COLON_TKN = 26;
  /** RegularExpression Id. */
  int SELECTOR_TKN = 27;
  /** RegularExpression Id. */
  int TAGS_TKN = 28;
  /** RegularExpression Id. */
  int BOOLEAN_TKN = 29;
  /** RegularExpression Id. */
  int INTEGER_TKN = 30;
  /** RegularExpression Id. */
  int BIT_TKN = 31;
  /** RegularExpression Id. */
  int STRING_TKN = 32;
  /** RegularExpression Id. */
  int OCTET_TKN = 33;
  /** RegularExpression Id. */
  int NULL_TKN = 34;
  /** RegularExpression Id. */
  int SEQUENCE_TKN = 35;
  /** RegularExpression Id. */
  int OF_TKN = 36;
  /** RegularExpression Id. */
  int SET_TKN = 37;
  /** RegularExpression Id. */
  int IMPLICIT_TKN = 38;
  /** RegularExpression Id. */
  int CHOICE_TKN = 39;
  /** RegularExpression Id. */
  int ANY_TKN = 40;
  /** RegularExpression Id. */
  int PRINTABLESTRING_TKN = 41;
  /** RegularExpression Id. */
  int GENERALIZEDTIME_TKN = 42;
  /** RegularExpression Id. */
  int GRAPHICSTRING_TKN = 43;
  /** RegularExpression Id. */
  int OPTIONAL_TKN = 44;
  /** RegularExpression Id. */
  int DEFAULT_TKN = 45;
  /** RegularExpression Id. */
  int COMPONENTS_TKN = 46;
  /** RegularExpression Id. */
  int UNIVERSAL_TKN = 47;
  /** RegularExpression Id. */
  int APPLICATION_TKN = 48;
  /** RegularExpression Id. */
  int PRIVATE_TKN = 49;
  /** RegularExpression Id. */
  int TRUE_TKN = 50;
  /** RegularExpression Id. */
  int FALSE_TKN = 51;
  /** RegularExpression Id. */
  int BEGIN_TKN = 52;
  /** RegularExpression Id. */
  int END_TKN = 53;
  /** RegularExpression Id. */
  int DEFINITIONS_TKN = 54;
  /** RegularExpression Id. */
  int EXPLICIT_TKN = 55;
  /** RegularExpression Id. */
  int AUTOMATIC_TKN = 56;
  /** RegularExpression Id. */
  int ENUMERATED_TKN = 57;
  /** RegularExpression Id. */
  int EXTERNAL_TKN = 58;
  /** RegularExpression Id. */
  int EXPORTS_TKN = 59;
  /** RegularExpression Id. */
  int IMPORTS_TKN = 60;
  /** RegularExpression Id. */
  int REAL_TKN = 61;
  /** RegularExpression Id. */
  int INCLUDES_TKN = 62;
  /** RegularExpression Id. */
  int CONTAINING_TKN = 63;
  /** RegularExpression Id. */
  int MIN_TKN = 64;
  /** RegularExpression Id. */
  int MAX_TKN = 65;
  /** RegularExpression Id. */
  int SIZE_TKN = 66;
  /** RegularExpression Id. */
  int FROM_TKN = 67;
  /** RegularExpression Id. */
  int WITH_TKN = 68;
  /** RegularExpression Id. */
  int COMPONENT_TKN = 69;
  /** RegularExpression Id. */
  int PRESENT_TKN = 70;
  /** RegularExpression Id. */
  int ABSENT_TKN = 71;
  /** RegularExpression Id. */
  int DEFINED_TKN = 72;
  /** RegularExpression Id. */
  int BY_TKN = 73;
  /** RegularExpression Id. */
  int PLUS_INFINITY_TKN = 74;
  /** RegularExpression Id. */
  int MINUS_INFINITY_TKN = 75;
  /** RegularExpression Id. */
  int OBJECTTYPE_TKN = 76;
  /** RegularExpression Id. */
  int SYNTAX_TKN = 77;
  /** RegularExpression Id. */
  int ACCESS_TKN = 78;
  /** RegularExpression Id. */
  int STATUS_TKN = 79;
  /** RegularExpression Id. */
  int DESCRIPTION_TKN = 80;
  /** RegularExpression Id. */
  int REFERENCE_TKN = 81;
  /** RegularExpression Id. */
  int INDEX_TKN = 82;
  /** RegularExpression Id. */
  int DEFVAL_TKN = 83;
  /** RegularExpression Id. */
  int DHINT = 84;
  /** RegularExpression Id. */
  int TC_TKN = 85;
  /** RegularExpression Id. */
  int MACRO_TKN = 86;
  /** RegularExpression Id. */
  int LCASEFIRST_IDENT_TKN = 87;
  /** RegularExpression Id. */
  int UCASEFIRST_IDENT_TKN = 88;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int WithinASNComment = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"--\"",
    "<token of kind 6>",
    "<token of kind 7>",
    "<OBJECT_IDENTIFIER_TKN>",
    "<BSTRING_TKN>",
    "<HSTRING_TKN>",
    "<CSTRING_TKN>",
    "<NUMBER_ERANGE_TKN>",
    "\"0\"",
    "\".\"",
    "\",\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"<\"",
    "\"-\"",
    "\"::=\"",
    "\"|\"",
    "\";\"",
    "\":\"",
    "\"TAGS\"",
    "\"BOOLEAN\"",
    "\"INTEGER\"",
    "\"BIT\"",
    "\"STRING\"",
    "\"OCTET\"",
    "\"NULL\"",
    "\"SEQUENCE\"",
    "\"OF\"",
    "\"SET\"",
    "\"IMPLICIT\"",
    "\"CHOICE\"",
    "\"ANY\"",
    "\"PrintableString\"",
    "\"GeneralizedTime\"",
    "\"GraphicString\"",
    "\"OPTIONAL\"",
    "\"DEFAULT\"",
    "\"COMPONENTS\"",
    "\"UNIVERSAL\"",
    "\"APPLICATION\"",
    "\"PRIVATE\"",
    "\"TRUE\"",
    "\"FALSE\"",
    "\"BEGIN\"",
    "\"END\"",
    "\"DEFINITIONS\"",
    "\"EXPLICIT\"",
    "\"AUTOMATIC\"",
    "\"ENUMERATED\"",
    "\"EXTERNAL\"",
    "\"EXPORTS\"",
    "\"IMPORTS\"",
    "\"REAL\"",
    "\"INCLUDES\"",
    "\"CONTAINING\"",
    "\"MIN\"",
    "\"MAX\"",
    "\"SIZE\"",
    "\"FROM\"",
    "\"WITH\"",
    "\"COMPONENT\"",
    "\"PRESENT\"",
    "\"ABSENT\"",
    "\"DEFINED\"",
    "\"BY\"",
    "\"PLUS-INFINITY\"",
    "\"MINUS-INFINITY\"",
    "\"OBJECT-TYPE\"",
    "\"SYNTAX\"",
    "\"ACCESS\"",
    "\"STATUS\"",
    "\"DESCRIPTION\"",
    "\"REFERENCE\"",
    "\"INDEX\"",
    "\"DEFVAL\"",
    "\"DISPLAY-HINT\"",
    "\"TEXTUAL-CONVENTION\"",
    "\"MACRO\"",
    "<LCASEFIRST_IDENT_TKN>",
    "<UCASEFIRST_IDENT_TKN>",
  };

}
