/* Generated By:JJTree: Do not edit this line. ASTBuiltinType.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public class ASTBuiltinType extends SimpleNode {

   private int type = -1;

   public ASTBuiltinType(int id) {
      super(id);
   }

   public ASTBuiltinType(AsnParser p, int id) {
      super(p, id);
   }

   public void setType(int type) {
      this.type = type;
   }

   public int getType() {
      return type;
   }

   /** Accept the visitor. **/
   @Override
   public Object jjtAccept(AsnParserVisitor visitor, Object data) {
      return visitor.visit(this, data);
   }
}
/* JavaCC - OriginalChecksum=b00b9c3634ff3820b09416a48d9af6e2 (do not edit this line) */
