/* Generated By:JJTree: Do not edit this line. ASTBitStringType.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public class ASTBitStringType extends SimpleNode {

   public ASTBitStringType(int id) {
      super(id);
   }

   public ASTBitStringType(AsnParser p, int id) {
      super(p, id);
   }

   /** Accept the visitor. **/
   public Object jjtAccept(AsnParserVisitor visitor, Object data) {
      return visitor.visit(this, data);
   }
}
/* JavaCC - OriginalChecksum=eba971a281796412749532e4c0c0ee78 (do not edit this line) */
