/* Generated By:JJTree: Do not edit this line. ASTBooleanType.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public class ASTBooleanType extends SimpleNode {

   public ASTBooleanType(int id) {
      super(id);
   }

   public ASTBooleanType(AsnParser p, int id) {
      super(p, id);
   }

   /** Accept the visitor. **/
   public Object jjtAccept(AsnParserVisitor visitor, Object data) {
      return visitor.visit(this, data);
   }
}
/* JavaCC - OriginalChecksum=990c8fe847bed31ff51fa066ff476cac (do not edit this line) */
