/* Generated By:JJTree: Do not edit this line. ASTChoiceType.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTChoiceType extends SimpleNode {
  public ASTChoiceType(int id) {
    super(id);
  }

  public ASTChoiceType(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b44d717abb63fde5d26566f14ed975f2 (do not edit this line) */
