/* Generated By:JJTree: Do not edit this line. ASTClassNumber.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public class ASTClassNumber extends SimpleNode {

   private int tagNumber;

   public ASTClassNumber(int id) {
      super(id);
   }

   public ASTClassNumber(AsnParser p, int id) {
      super(p, id);
   }

   public void setTagNumber(int tagNumber) {
      this.tagNumber = tagNumber;
   }

   public int getTagNumber() {
      return this.tagNumber;
   }

   /** Accept the visitor. **/
   public Object jjtAccept(AsnParserVisitor visitor, Object data) {
      return visitor.visit(this, data);
   }
}
/* JavaCC - OriginalChecksum=8aeabff4a3da467d0754f769397c72cc (do not edit this line) */
