/* Generated By:JJTree: Do not edit this line. ASTDefinedMacroType.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTDefinedMacroType extends SimpleNode {
  public ASTDefinedMacroType(int id) {
    super(id);
  }

  public ASTDefinedMacroType(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2bdde9e681ff8b6f4961abfbc48a9ece (do not edit this line) */
