/* Generated By:JJTree: Do not edit this line. ASTDisplayHint.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTDisplayHint extends SimpleNode {
  public ASTDisplayHint(int id) {
    super(id);
  }

  public ASTDisplayHint(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9999b73b5c9acd7b15982da905d458f0 (do not edit this line) */
