/* Generated By:JJTree: Do not edit this line. ASTEnumeratedType.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public class ASTEnumeratedType extends SimpleNode {

   public ASTEnumeratedType(int id) {
      super(id);
   }

   public ASTEnumeratedType(AsnParser p, int id) {
      super(p, id);
   }

   /** Accept the visitor. **/
   public Object jjtAccept(AsnParserVisitor visitor, Object data) {
      return visitor.visit(this, data);
   }
}
/* JavaCC - OriginalChecksum=0e2e5a57962232ed0487a0418f9332d1 (do not edit this line) */
