/* Generated By:JJTree: Do not edit this line. ASTExportSymbolList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTExportSymbolList extends SimpleNode {
  public ASTExportSymbolList(int id) {
    super(id);
  }

  public ASTExportSymbolList(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=583bd16ba9a59997a5cd06068785fb3f (do not edit this line) */
