/* Generated By:JJTree: Do not edit this line. ASTIntegerType.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public class ASTIntegerType extends SimpleNode {

   public ASTIntegerType(int id) {
      super(id);
   }

   public ASTIntegerType(AsnParser p, int id) {
      super(p, id);
   }

   /** Accept the visitor. **/
   public Object jjtAccept(AsnParserVisitor visitor, Object data) {
      return visitor.visit(this, data);
   }
}
/* JavaCC - OriginalChecksum=a5a3b80ba221fd9af4e92ea79c25c9f9 (do not edit this line) */
