/* Generated By:JJTree: Do not edit this line. ASTNameAndNumberForm.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTNameAndNumberForm extends SimpleNode {
  public ASTNameAndNumberForm(int id) {
    super(id);
  }

  public ASTNameAndNumberForm(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2fe8c55b7ceaffb3236c4634e5eb11aa (do not edit this line) */
