/* Generated By:JJTree: Do not edit this line. ASTNamedNumberList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTNamedNumberList extends SimpleNode {
  public ASTNamedNumberList(int id) {
    super(id);
  }

  public ASTNamedNumberList(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4993d2556d54d3bea7b1fc5418543cd5 (do not edit this line) */
