/* Generated By:JJTree: Do not edit this line. ASTNamedConstraint.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTNamedConstraint extends SimpleNode {
  public ASTNamedConstraint(int id) {
    super(id);
  }

  public ASTNamedConstraint(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=38445f7d0cacdf085f3855328cc90b4e (do not edit this line) */
