/* Generated By:JJTree: Do not edit this line. ASTObjIdComponent.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTObjIdComponent extends SimpleNode {
  public ASTObjIdComponent(int id) {
    super(id);
  }

  public ASTObjIdComponent(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6c4580c569297c9c4b784d2bcd94e625 (do not edit this line) */
