/* Generated By:JJTree: Do not edit this line. ASTObjIdComponentList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTObjIdComponentList extends SimpleNode {
  public ASTObjIdComponentList(int id) {
    super(id);
  }

  public ASTObjIdComponentList(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d1fbb66b881de9a66026e21efb4a8cbd (do not edit this line) */
