/* Generated By:JJTree: Do not edit this line. ASTSpecialRealValue.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTSpecialRealValue extends SimpleNode {
  public ASTSpecialRealValue(int id) {
    super(id);
  }

  public ASTSpecialRealValue(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=bdedb4990a87785eb31dfa72781b11c3 (do not edit this line) */
