/* Generated By:JJTree: Do not edit this line. ASTSnmpStatus.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTSnmpStatus extends SimpleNode {
  public ASTSnmpStatus(int id) {
    super(id);
  }

  public ASTSnmpStatus(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=377fde3fcf3a11fa028e736efe6590a1 (do not edit this line) */
