/* Generated By:JJTree: Do not edit this line. ASTSingleTypeConstraint.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTSingleTypeConstraint extends SimpleNode {
  public ASTSingleTypeConstraint(int id) {
    super(id);
  }

  public ASTSingleTypeConstraint(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=36475a18692d5765edc777d12a13e4e8 (do not edit this line) */
