/* Generated By:JJTree: Do not edit this line. ASTSetOrSequenceOfType.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTSetOrSequenceOfType extends SimpleNode {
  public ASTSetOrSequenceOfType(int id) {
    super(id);
  }

  public ASTSetOrSequenceOfType(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6022c53bc86695d1f79f8752b9e37002 (do not edit this line) */
