/* Generated By:JJTree: Do not edit this line. ASTSnmpDefValPart.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTSnmpDefValPart extends SimpleNode {
  public ASTSnmpDefValPart(int id) {
    super(id);
  }

  public ASTSnmpDefValPart(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=08cb9dc6ff9bbd918a1f361d2af3b5f7 (do not edit this line) */
