/* Generated By:JJTree: Do not edit this line. ASTSymbolsImported.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTSymbolsImported extends SimpleNode {
  public ASTSymbolsImported(int id) {
    super(id);
  }

  public ASTSymbolsImported(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5a44392deb16c27e3e4fc2f71af861df (do not edit this line) */
