/* Generated By:JJTree: Do not edit this line. ASTSymbolsFromModuleList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTSymbolsFromModuleList extends SimpleNode {
  public ASTSymbolsFromModuleList(int id) {
    super(id);
  }

  public ASTSymbolsFromModuleList(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f2de41d849c3dc7aa4e76a0addf11770 (do not edit this line) */
