/* Generated By:JJTree: Do not edit this line. ASTSnmpDescrPart.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTSnmpDescrPart extends SimpleNode {
  public ASTSnmpDescrPart(int id) {
    super(id);
  }

  public ASTSnmpDescrPart(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b615d669f245993215f1d331a9c334bf (do not edit this line) */
