/* Generated By:JJTree: Do not edit this line. ASTSetOrSequenceType.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public class ASTSetOrSequenceType extends SimpleNode {

   public static final int SEQUENCE = 0;
   public static final int SET = 1;
   int choosenType = -1;

   public ASTSetOrSequenceType(int id) {
      super(id);
   }

   public ASTSetOrSequenceType(AsnParser p, int id) {
      super(p, id);
   }

   public void setType(int type) {
      choosenType = type;
   }

   public int getType() {
      return this.choosenType;
   }

   public boolean isSequence() {
      return choosenType == SEQUENCE;
   }

   public boolean isSet() {
      return choosenType == SET;
   }

   /** Accept the visitor. **/
   public Object jjtAccept(AsnParserVisitor visitor, Object data) {
      return visitor.visit(this, data);
   }
}
/* JavaCC - OriginalChecksum=2094e8a0b44149ce72389a6121343e53 (do not edit this line) */
