/* Generated By:JJTree: Do not edit this line. ASTSymbolsExported.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTSymbolsExported extends SimpleNode {
  public ASTSymbolsExported(int id) {
    super(id);
  }

  public ASTSymbolsExported(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e2cfcfd2278fbf79783cd2845635d57f (do not edit this line) */
