/* Generated By:JJTree: Do not edit this line. ASTTypeAssignment.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public class ASTTypeAssignment extends SimpleNode {

   public static int BUILTIN_ASSIGNMENT = 1;
   public static int DEFINED_ASSIGNMENT = 2;
   int assignment = -1;

   public ASTTypeAssignment(int id) {
      super(id);
   }

   public ASTTypeAssignment(AsnParser p, int id) {
      super(p, id);
   }

   public void setAssignment(int assignment) {
      this.assignment = assignment;
   }

   public boolean isBuiltIn() {
      return this.assignment == BUILTIN_ASSIGNMENT;
   }

   public boolean isDefined() {
      return this.assignment == DEFINED_ASSIGNMENT;
   }

   /** Accept the visitor. **/
   public Object jjtAccept(AsnParserVisitor visitor, Object data) {
      return visitor.visit(this, data);
   }
}
/* JavaCC - OriginalChecksum=75503f5eaadfec49a9d1bc81edae7d2c (do not edit this line) */
