/* Generated By:JJTree: Do not edit this line. ASTTaggedType.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public class ASTTaggedType extends SimpleNode {

   public static final int IMPLICIT = 0;
   public static final int EXPLICIT = 1;
   public static final int CONTEXT = 0;
   public static final int UNIVERSAL = 1;
   public static final int APPLICATION = 2;
   public static final int PRIVATE = 3;
   private int tm = EXPLICIT;

   public ASTTaggedType(int id) {
      super(id);
   }

   public ASTTaggedType(AsnParser p, int id) {
      super(p, id);
   }

   public void setTaggingMethod(int tm) {
      this.tm = tm;
   }

   public boolean isImplicitTagging() {
      return tm == IMPLICIT;
   }

   public boolean isExplicitTagging() {
      return tm == EXPLICIT;
   }

   /** Accept the visitor. **/
   public Object jjtAccept(AsnParserVisitor visitor, Object data) {
      return visitor.visit(this, data);
   }
}
/* JavaCC - OriginalChecksum=03517d402d807129336575f3b5a8feaf (do not edit this line) */
